%Created by Kriston Rickman
%Date created 09/03/26
%v1_12 for Energy based constraint analysis v1_39
%States 
%Notes: 



classdef Aircraft_constraint_states
    enumeration
        MAIN_MENU
        SAVED_TW_AIRCRAFT_DATA
        USER_TW_AIRCRAFT_MENU
        EDIT_SAVED_TW_AIRCRAFT
        GET_TW_AIRCRAFT_DATA
        CALCULATE_TW
        GRAPH_TW
        CALCULATE_TW_FROM_USER_TW_DATA_CALCULATION
        GRAPH_TW_FROM_USER_TW_DATA_CALCULATION
        GET_ST_AIRCRAFT_DATA
        CALCULATE_ST
        GRAPH_ST
        SAVED_ST_AIRCRAFT_DATA
        USER_ST_AIRCRAFT_MENU
        EDIT_SAVED_ST_AIRCRAFT
        CALCULATE_ST_FROM_USER_ST_DATA_CALCULATION
        GRAPH_ST_FROM_USER_ST_DATA_CALCULATION
        GET_LOADS_AIRCRAFT_DATA
        CALCULATE_LOADS
        GRAPH_LOADS
        SAVED_LOADS_AIRCRAFT_DATA
        USER_LOADS_AIRCRAFT_MENU
        CALCULATE_LOADS_FROM_USER_LOADS_DATA_CALCULATION
        GRAPH_LOADS_FROM_USER_LOADS_DATA_CALCULATION

        ERROR_STATE %need to create
    end
end